allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "BSD-3-Clause-Modification",
    "ISC",
    "MPL-2.0",
]

deny  = [
    "AGPL-1.0-only",
    "AGPL-1.0-or-later",
    "AGPL-3.0-only",
    "AGPL-3.0-or-later",
    "GPL-1.0-only",
    "GPL-1.0-or-later",
    "GPL-2.0-only",
    "GPL-2.0-or-later",
    "GPL-3.0-only",
    "GPL-3.0-or-later",
    "LGPL-2.0-only",
    "LGPL-2.0-or-later",
    "LGPL-2.1-only",
    "LGPL-2.1-or-later",
    "LGPL-3.0-only",
    "LGPL-3.0-or-later",
    "LGPLLR",
    "AGPL-1.0",
    "AGPL-3.0",
    "GPL-1.0",
    "GPL-1.0+",
    "GPL-2.0",
    "GPL-2.0+",
    "GPL-2.0-with-autoconf-exception",
    "GPL-2.0-with-bison-exception",
    "GPL-2.0-with-classpath-exception",
    "GPL-2.0-with-font-exception",
    "GPL-2.0-with-GCC-exception",
    "GPL-3.0",
    "GPL-3.0+",
    "GPL-3.0-with-autoconf-exception",
    "GPL-3.0-with-GCC-exception",
    "LGPL-2.0",
    "LGPL-2.0+",
    "LGPL-2.1",
    "LGPL-2.1+",
    "LGPL-3.0",
    "LGPL-3.0+",
]

override = {
   "github.com/gogo/protobuf"           = "BSD-3-Clause-Modification",
   "github.com/rcrowley/go-metrics"     = "BSD-3-Clause-Modification",
   "github.com/xeipuuv/gojsonschema"    = "Apache-2.0",
   "github.com/xeipuuv/gojsonreference" = "Apache-2.0",
   "github.com/xeipuuv/gojsonpointer"   = "Apache-2.0",
   "gopkg.in/square/go-jose.v2"         = "Apache-2.0",
   "github.com/pelletier/go-toml"       = "MIT",
   "sigs.k8s.io/yaml"                   = "MIT",
   "github.com/ghodss/yaml"             = "MIT",
}
