settings:
  name: OSS Triage

fairwinds-repos: &fairwinds-repos
  - https://github.com/fairwindsops/pluto
  - https://github.com/fairwindsops/goldilocks
  - https://github.com/fairwindsops/rbac-manager
  - https://github.com/fairwindsops/rbac-lookup
  - https://github.com/fairwindsops/nova
  - https://github.com/fairwindsops/polaris

helm-repos: &helm-repos
  - https://github.com/helm/helm
  - https://github.com/helm/community

collections:
  - id: helm
    name: Helm
    rules:
      - pr-unreviewed
    repos: *helm-repos
  - id: fairwinds
    name: Fairwinds
    rules:
      - pr-unreviewed
      - issue-triage
    repos: *fairwinds-repos
  - id: fairwinds-dependabot
    name: FW Dependabot
    rules:
      - dependabot
    repos: *fairwinds-repos

rules:
  pr-unreviewed:
    name: "Un-Reviewed"
    type: pull_request
    filters:
      - title: "!.*(WIP|wip).*"
      - tag: "!draft"
      - label: "!dependencies"
      - tag: "unreviewed"
  issue-triage:
    name: "Issue Triage"
    type: issue
    filters:
      - label: "!dependencies"
      - label: "triage"
  dependabot:
    name: "Dependabot"
    type: pull_request
    filters:
      - label: "dependencies"
