fairwinds-oss: &fairwinds-stable-oss-repos
  - https://github.com/fairwindsops/pluto
  - https://github.com/fairwindsops/nova
  - https://github.com/fairwindsops/polaris
  - https://github.com/fairwindsops/goldilocks
  - https://github.com/fairwindsops/rbac-lookup
  - https://github.com/fairwindsops/rbac-manager
  - https://github.com/fairwindsops/reckoner
  - https://github.com/fairwindsops/charts
  - https://github.com/fairwindsops/insights-plugins
  - https://github.com/fairwindsops/rok8s-scripts
settings:
  name: Fairwinds Triage
  min_similarity: 0.8

collections:
  - id: fw-dependabot
    category: fairwinds-stable
    name: Dependabot
    dedup: true
    description: >
      Fairwinds Dependabot Pull Requests (PRs)
    rules:
      - dependabot-docker
      - dependabot-go
      - dependabot-other
    repos: *fairwinds-stable-oss-repos
  - id: fw-prs
    category: fairwinds-stable
    name: Pull Requests (PRs)
    dedup: true
    description: >
      Fairwinds PRs that might be good to review/merge
    rules:
      - pr-reviewable
      - pr-mergeable
    repos: *fairwinds-stable-oss-repos
  - id: fw-triage-issues
    category: fairwinds-stable
    name: Issue Triage
    description: >
      Fairwinds Issues w/ Triage Label
    rules:
      - triage-bugs
      - triage-enhancements
      - triage-other
    repos: *fairwinds-stable-oss-repos
  - id: fw-all-issues
    category: fairwinds-stable
    name: All Issues
    description: >
      Fairwinds Issues (all minus dependabot)
    rules:
      - fw-bugs
      - fw-enhancements
      - fw-issues-other
    repos: *fairwinds-stable-oss-repos
rules:
  pr-reviewable:
    name: "Pull Requests: Review Ready"
    resolution: "Review requests or mark them as do-not-merge/work-in-progress"
    type: pull_request
    filters:
      - title: "!.*(WIP|wip).*"
      - label: "!Don't Merge!!"
      - label: "!needs-rebase"
      - label: "!dependencies"
      - tag: "!approved"
  pr-mergeable:
    name: "PRs to Merge"
    resolution: "Merge the PR"
    type: pull_request
    filters:
      - title: "!Don't Merge!!"
      - tag: "approved"
  dependabot-docker:
    name: "Dependabot Docker"
    type: pull_request
    resolution: Review, approve, and merge the PR
    filters:
      - label: dependencies
      - label: docker
  dependabot-go:
    name: "Dependabot Golang"
    type: pull_request
    resolution: Review, approve, and merge the PR
    filters:
      - label: dependencies
      - label: go
  dependabot-other:
    name: "Dependabot All Others"
    type: pull_request
    resolution: Review, approve, and merge the PR
    filters:
      - label: dependencies
      - label: "!docker"
      - label: "!go"
  triage-bugs:
    name: "Triage Bugs"
    resolution: |
      Review the issue and respond appropriately. Remove the triage label and add any other necessary labels.
    type: issue
    filters:
      - label: triage
      - label: bug
  triage-enhancements:
    name: "Triage Enhancements"
    resolution: |
      Review the issue and respond appropriately. Remove the triage label and add any other necessary labels.
    type: issue
    filters:
      - label: triage
      - label: enhancement
  triage-other:
    name: "Triage All Others"
    type: issue
    filters:
      - label: triage
      - label: "!enhancement"
      - label: "!bug"
  fw-bugs:
    name: All Bugs
    type: issue
    filters:
      - label: bug
  fw-enhancements:
    name: All Enhancements
    type: issue
    filters:
      - label: enhancement
  fw-issues-other:
    name: Other Issues
    type: issue
    filters:
      - label: "!bug"
      - label: "!enhancement"

