---
helm-repos: &helm-repos
  - https://github.com/helm/helm
  - https://github.com/helm/community

fairwinds-oss: &fairwinds-stable-oss-repos
  - https://github.com/fairwindsops/pluto
  - https://github.com/fairwindsops/nova
  - https://github.com/fairwindsops/polaris
  - https://github.com/fairwindsops/goldilocks
  - https://github.com/fairwindsops/rbac-manager
  - https://github.com/fairwindsops/reckoner

settings:
  name: Andy's Triage
  min_similarity: 0.8

collections:
  - id: helmpr
    category: helm
    name: Helm PRs To Review
    dedup: true
    description: >
      Helm PRs that might be good to review
    rules:
      - pr-reviewable
    repos: *helm-repos

  - id: fw-dependabot
    category: fairwinds-stable
    name: Fairwinds Dependabot PRs
    dedup: true
    description: >
      Fairwinds Dependabot PRs
    rules:
      - dependabot
    repos: *fairwinds-stable-oss-repos

  - id: fw-prs
    category: fairwinds-stable
    name: Fairwinds PRs to Review
    dedup: true
    description: >
      Fairwinds PRs that might be good to review
    rules:
      - pr-reviewable
    repos: *fairwinds-stable-oss-repos
rules:
  # Don't leave code reviews hanging
  pr-reviewable:
    name: "Pull Requests: Review Ready"
    resolution: "Review requests or mark them as do-not-merge/work-in-progress"
    type: pull_request
    filters:
      - title: "!.*(WIP|wip).*"
      - label: "!do-not-merge.*"
      - label: "!needs-rebase"
      - label: "!dependencies"
      - tag: "!changes-requested"
      - tag: "!approved"
      - tag: "!reviewed-with-comment"
  dependabot:
    name: "Dependabot"
    type: pull_request
    filters:
      - label: "dependencies"
